#!/bin/bash
: <<LICENSE
      rwfus: Rwfus - RW OverlayFS for Deck!
    Copyright (C) 2022 ValShaped (val@soft.fish)

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Lesser General Public
    License as published by the Free Software Foundation; either
    version 2.1 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public
    License along with this library; if not, write to the Free Software
    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
LICENSE
caller_dir=${PWD}
caller_cmd="$0 $@"

cd $(dirname "$BASH_SOURCE[0]")
source rwfus_include/info.sh           # Project information (name, etc.)
source rwfus_include/testlog.sh        # Logging
source rwfus_include/service.sh        # Generate and manage service and associated unit file
source rwfus_include/disk.sh           # Generate and manage disk images
source rwfus_include/manage-install.sh # Installation management
source rwfus_include/config.sh         # Configuration files

# Load the default configuration.
load_defaults

# Default operation
Default_Operation="stat_service "

function print_help {
    cat <<EOF
$Name v$Version
$Description

USAGE:
    $0 [FLAGS] [OPTIONS] [--] [DIRECTORY]...

FLAGS:
    -h, --help          Show this help text, then exit
    -v, --version       Show the version number, then exit

    -i, --install*      Install $Name
    -u, --update*       Re-generate systemd service files, without touching data
    -r, --remove*       Remove ALL FILES AND DIRECTORIES associated with $Name

    -e, --enable*       Activate overlays
    -d, --disable*      Deactivate overlays
    -s, --status        Get the status of the overlay-mounter and disk image

        --mount*        Mount $Name's disk image
        --umount*       Unmount $Name's disk image

    -I, --install-bin*  Put $0 into a [...]/usr/local/bin folder
    -R, --remove-bin*   Remove $Name from a [...]/usr/local/bin folder

    -t, --test          Use fake directory targets when performing operations
    -g, --gen-config    Generate a sample config file, which you can use to customize your install

    * flags marked with a star require root, unless the --test flag is set.

    OPTIONS:
    -l, --logfile <path>    Specify the location of $Name's log file
                                Default: $Log_File (where X is random)
    -c, --config <path>     Specify a configuration file to use
                                Default: $Base_Directory/

        --backup <dest>*    Backup $Name's disk image to (file path) <dest>
        --restore <src>*    Restore $Name's disk image from (file path) <src>

    * options marked with a star require root, unless the --test flag is set.

ARGS:
    <DIRECTORY>...          List of directories to create overlays for
                                Defaults: $Directories
EOF
}

# Parse options
LONGOPTS="help,install,update,remove,enable,disable,status,mount,umount,backup:,restore:,test,version,install-bin,remove-bin,gen-config,gen-script,gen-disk,logfile:,config:"
SHORTOPTS="hiuredstvIRgl:c:"
PARSED=`getopt --options "$SHORTOPTS" --longoptions "$LONGOPTS" --name $0 -- $@`
if [[ $? != 0 ]]; then
    echo "Usage: $0 [-hiuredstvg] [-l path/to/logfile] [-c path/to/config] [/dir1 /dir2 ...]"
    exit -128;
fi
eval set -- "$PARSED"

while true; do
    case "$1" in
    # Get information
        -h|--help)
            Operation+="print_help "
            shift
        ;;
        -v|--version)
            Operation+="version "
            shift
        ;;
    # Installation operations
        -i|--install)
            Operation+="perform_install "
            shift
            ;;
        -u|--update)
            Operation+="perform_update "
            shift
            ;;
        -r|--remove)
            Operation+="perform_remove_all "
            shift
            ;;
    # Enablement control operations
        -e|--enable)
            Operation+="enable_service stat_service "
            shift
            ;;
        -d|--disable)
            Operation+="disable_service stat_service "
            shift
            ;;
        -s|--status)
            Operation+="stat_service stat_disk "
            shift
            ;;
    # Disk Image Control
        --mount)
            Operation+="mount_disk "
            shift
        ;;
        --umount|--unmount)
            Operation+="unmount_disk "
            shift
        ;;
        --backup)
            Operation+="backup_disk "
            disk_path="$2"
            shift 2
        ;;
        --restore)
            Operation+="restore_disk "
            disk_path="$2"
            shift 2
        ;;
    # Test mode
        -t|--test)
            enable_testmode
            shift
            ;;
    # Sample generators
        -g|--gen-config)
            sample_fullpath="$caller_dir/${Name@L}.conf"
            config --store "$sample_fullpath"
            echo "Wrote config to $sample_fullpath"
            exit 0
            ;;
        --gen-script)
            sample_fullpath="$caller_dir/${Name@L}d.sh"
            generate_service_script > "$sample_fullpath"
            echo "Wrote script to $sample_fullpath"
            exit 0
            ;;
        --gen-disk)
            shift 2
            sample_fullpath="$caller_dir/${Name@L}.btrfs"
            generate_disk_image "$sample_fullpath" $@
            echo "Wrote disk image to $sample_fullpath"
            exit 0
            ;;
    # on-path installation
        -I|--install-bin)
            Operation+="add_to_bin "
            shift
        ;;
        -R|--remove-bin)
            Operation+="remove_from_bin "
            shift
        ;;
    # Options
        -l|--logfile)
            Log_File="$2"
            shift 2
            ;;
        -c|--config)
            Config_File="$2"
            load_config $Config_File
            shift 2
            ;;

        --)
            shift
            break
            ;;
        *)
            echo "You've encountered unreachable path #1, invalid arg \"$1\"! Please tell a developer right away."
            exit -1
            ;;
    esac
done


function initialize_log {
    if [[ ! $LOG_INITIALIZED ]]; then
        LOG_INITIALIZED=true
        Log --new
        Log echo $caller_cmd
        trap get_logfile_name EXIT
    fi
}

for operation in ${Operation:=$Default_Operation}; do
    case "$operation" in
        "perform_install"|"perform_update"|"perform_remove_all"|\
        "add_to_bin"|"remove_from_bin"|\
        "enable_service"|"disable_service")
            check_permissions
            initialize_log
            Log config --load
            $operation $@
        ;;
        "mount_disk"|"unmount_disk"|"backup_disk"|"restore_disk")
            check_permissions
            config --load
            if [[ service_state =~ "enabled" ]]; then
                disable_service
                $operation $disk_path
                enable_service
            else
                $operation $disk_path
            fi
        ;;
        "stat_service"|"stat_disk")
            $operation
        ;;
        "print_help")
            $operation
            exit 0
        ;;
        "version")
            printf "$Name v$Version\n$Description\n"
        ;;
        *)
            trap get_logfile_name EXIT
            initialize_log
            Log -p echo "You've encountered unreachable path #2, invalid operation \"$operation\"! Contact a developer and let them know!"
            exit -1
        ;;
    esac
done
exit 0
